name: Render Video

on:
  workflow_dispatch:
    inputs:
      sceneId:
        description: 'The ID of the Composition to render (e.g., GoldGraph, RunningMan)'
        required: true
        default: 'RunningMan'

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Render Video
        run: npx remotion render ${{ github.event.inputs.sceneId }} out/video.mp4

      - name: Upload Finished MP4
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.sceneId }}-Video
          path: out/video.mp4
